Summer QA task 2024
maximeftodii/summer-qa-task-2024 pull request #2
Opened 2024-08-19 22:10 UTC by maximeftodii

2024-08-19 22:18 UTC, maximeftodii commented
I have never worked with forks on github so might've done something wrong.

2024-08-21 13:18 UTC, tommy-anderson requested changes
Salutare Maxim 👋 

O sa folosesc acest PR ca sa dau feedback pentru tot homework-ul.

### Bug Report
La capitolul de bug report - kudos 👍 - e bine structurat si are toate campurile necesare (title, summary, severity, steps to reproduce, etc. )
La bug hunting insa mai multe chestii as vrea sa evidentiez.
1. Ai raportat un bug cum ca `When a task is created, it is set to a completed status by default, even though it should be set to incomplete.` - probabil te-a dus in eroare textul de pe butonul `Complete` - care e un buton care va transforma taskul in completed. Deci asta nu e un bug valid. in cel mai bun caz - ar putea fi interpretat ca UX improvement pentru ca dupa cum vedem - userii acestui app - ar putea sa faca aceiasi interpretare eronata.
2. Din pacate ai raportat cam putine buguri - Ele sunt intre 15 si 20 in dependenta de cum le grupezi . Vreo 10 functionale si vreo 10 de UI/UX. Imi pare rau ca ti-au scapat chestii ca 
```
* User is able to create task without a title
* User can edit task title to not be capitalized
* Task gets completed when entering edit mode and cancelling the edit.
* Task is set to Label: Hobby and Priority: Low if editing title and/or description only.
* Tasks with the same title get deleted.
* Loading cursor on Edit button
* Text cursor on Cancel Edit button
```
si altele.

### Automation
La automation am vazut ca ai automatizat 4 actiuni ale userilor.
In instructiuni se scria de automatizat 5 user stories si 3 regression bugs. Asa ca aici nu ai completat pe deplin taskul.

Aditional am vazut ca modul cum ai structurat pagina de MainPage a luat in considerare doar testele care vroiai sa le scrii acum. De obicei cand se declara metode si componente pentru PageObjects trebuie sa ne gandim la faptul ca clasele si metodele astea vor fi folosite de alti stakeholderi ( alti QA, Devi, DevOps etc. ) asa ca ele trebuie sa fie generice, nu particulare.

La tine functii ca `createNewTask` si `editTask` folosesc valori hardcodate doar pentru testele tale - pe cand ar trebui sa fie parametrizate in dependenta de chestiile relevante pentru taskuri - task title, deccription, importance, label etc.

O sa vezi mai mult context in comentariile la bucatile de cod anume

### Conclusion
Iti multumesc frumos pentru ca ti-ai luat din timp sa incerci Playwright si ca ai dedicat efort pentru executarea taskurilor din Homework. That being said - aveam asteptari mai mari de la candidatul pentru aceasta pozitie. Iti urez bafta pe viitor!

2024-08-21 13:18 UTC, tommy-anderson commented on .github/workflows/playwright.yml
> +name: Playwright Tests
appreciate the GH Action 👍

2024-08-21 13:18 UTC, tommy-anderson commented on src/tests/PageObjects/MainPage.ts
> +    private createTaskName(increment: boolean = true): string {
curios ca ai ales sa hardcodezi numele la title, any reason why? 🤔

2024-08-21 13:18 UTC, tommy-anderson commented on src/tests/PageObjects/MainPage.ts
> +    async createNewTask() {
M-as astepta ca metoda asta sa primeasca ca parametru title, description, label si importance. Asa ea poate fi folosita ca sa creeze doar un anumit tip de taskuri. Daca alt QA vrea sa creeze un task cu un nume lung, sau care sa se inceapa cu un numar, sau un caracter special etc.

2024-08-21 13:18 UTC, tommy-anderson commented on src/tests/PageObjects/MainPage.ts
> +        await expect(this.page.getByText(taskName)).toBeVisible();
aici din pacate to nu e okay, ca this.page.getByText o sa gaseasca pe toata pagina daca este textul - scopul nostru insa este sa vedem daca este un task cu acest taskname si acest task description.

De exemplu in cazul tau daca tu taskurile
```
Title: Task something
Description: description

Title: Task 
Description: Description whatever
```

Si chemi metoda `verifyCreatedTask('something', 'whatever' )` - ea o sa treaca pentru ca o sa gaseasca asa title si description - insa nu ar trebui, pentru ca nu este asa task.

Aici ar trebui sa te legi de un anumit `.task-item` si sa verifici anume descrierea si titlul in interiorul ei.

2024-08-21 13:18 UTC, tommy-anderson commented on src/tests/PageObjects/MainPage.ts
> +    async editTask() {
la fel aici ma astept sa vad parametri la metoda
Ce task editez? care aspecte le editez - title, description, importance, label ?

2024-08-21 13:18 UTC, tommy-anderson commented on src/tests/PageObjects/MainPage.ts
> +    async verifyEditedTask(editedTaskName: string, editedDescription: string): Promise<void> {
Aici nu ar trebui sa avem o functie separata, ci sa folosim verifyTask.

2024-08-21 13:18 UTC, tommy-anderson commented on src/tests/PageObjects/MainPage.ts
> +    async deleteTask() {
la fel ma astept parametru la ce task facem delete 🤔

2024-08-21 13:18 UTC, tommy-anderson commented on src/tests/PageObjects/MainPage.ts
> +    async importanceDropdonwSelection(importance: string) {
pentru ca aici facem o actiune - functia ar trebui sa aiba un verb in ea 
`selectImportance`

2024-08-21 13:18 UTC, tommy-anderson commented on src/tests/PageObjects/MainPage.ts
> +    async labelDropdownSelection(label: string) {
same as above

2024-08-21 13:18 UTC, tommy-anderson commented on src/tests/PageObjects/MainPage.ts
> +    async selectTaskOptions(importance: string, label: string) {
nu e necesar o functie care in interior cheama alte doua functii publice

2024-08-21 13:18 UTC, tommy-anderson commented on src/tests/Tests.spec.ts
> +    execPromise(runApp);
Acest pattern de a starta aplicatia la beforeAll - prima data il vad 🤔 

Vad multe dezavantaje la el - daca faci development la teste in acest fisier - o sa se porneasca prima data, si dupa asta o sa se ruleze fara scop 🤷 

Plus pentru ca se executa in alt terminal folosind exec - nu stim daca s-a pornit sau nu , daca au fost erori sau nu.

2024-08-21 13:55 UTC, maximeftodii commented
Salut! Multumesc de feedback. 

La partea de bug report nu a fost clar pentru mine ca trebuia de raportat absolut toate defectele gasite, posibil formularea era asa sau eu nu am inteles corect.
La partea de automation, parametrizare is deacord cam cu tot. Problema era in faptul ca Tylescript si Playwright e ceva nou pentru mine si majoritatea timpului s-a dus pe documentatie si invatare. Sigur ca e posibil si trebuie de facut metode parametrizate dar timpul limitat m-a incurcat sa fac asta peste tot. 
Multumesc inca o data de feedback, a fost challenging si interesant.

2024-08-26 06:27 UTC, merged